parameters:

services:
    app.password_change.changer:
        class: AppBundle\Cabinet\PasswordChange\Changer
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.password_encoder'
            - "@=service('security.token_storage').getToken().getUser()"
